///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest99
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTest99Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("361e5c17-eb48-47ab-b4f4-6b45bf0b0f18")]
    public partial class MyTest99Repository : RepoGenBaseFolder
    {
        static MyTest99Repository instance = new MyTest99Repository();

        /// <summary>
        /// Gets the singleton class instance representing the MyTest99Repository element repository.
        /// </summary>
        [RepositoryFolder("361e5c17-eb48-47ab-b4f4-6b45bf0b0f18")]
        public static MyTest99Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTest99Repository() 
            : base("MyTest99Repository", "/", null, 0, false, "361e5c17-eb48-47ab-b4f4-6b45bf0b0f18", ".\\RepositoryImages\\MyTest99Repository361e5c17.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("361e5c17-eb48-47ab-b4f4-6b45bf0b0f18")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTest99RepositoryFolders
    {
    }
#pragma warning restore 0436
}
